spring:
  devtools:
    restart:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: gbajsdpstltm

mybatis:
  mapper-locations: mapper/*.xml


server:
  port: 8081